[project]
name = "claude-agent-on-agentcore-frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.45",
    "streamlit>=1.50.0",
]
